name: CI

on:
  push:
    branches: '**'
    paths: 
      - 'Randomizer/**'
      - '.github/**'
  pull_request:
    branches: '**'
    paths: 
      - 'Randomizer/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Prepare
      run: mkdir -p ${{ github.workspace }}/dist

    - name: Build and Bundle
      run: bash ${{ github.workspace }}/bundle.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CelesteRandomizer
        path: ${{ github.workspace }}/dist/Randomizer_*.zip

